version: "3.7"

networks:
  default:
    driver: bridge

services:
  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    working_dir: /home
    volumes:
      - ./.db:/var/lib/postgresql/data
      - .:/home
